### ISSUE TITLE
Add automatic response for performance mention

### ISSUE THREAD

**Issue by qezz** [jerk-rs/autoresponsebot#2]
Need to add an automatic reply when PERFORMANCE is mentioned

the possible template may be as following:

> У нас в JetBrains эксперимент проводили - переписали библиотеку miniz с Си на Rust (ну не С++, а Си, окей). miniz - это сейчас типа самая убероптимизированная inflate/deflate либа, быстрее zlib. Соотв. inflate/deflate - это чистая числодробилка. Есть массив байт на входе, нужно получить другой массив байт на выходе. Только алгоритм реализуй. Ну эта "убероптимизированность" miniz выражается в т.ч. в экстремально нечитаемом коде, где все состоит из макросов со всякими нелокальными goto и прочим. Полное адище.
На Rust переписыали буквально по одной функции - Rust с Си превосходно линкуется. Т.е. БУКВАЛЬНО по одной функции переписывали, линковали и прогоняли тесты. Т.е. один в один вся реализация и структура программы сохранены остались. Как переписано было все, уже начали рефакторить. Короче получился очень красивый и читаемый код, просто ни в какое сравнение с оригиналом. Кроме того, блягодаря расту получаем статически гарантируемый type/memory safety. А дальше уже стали ЕГО ОПТИМИЗИРОВАТЬ ЕЩЕ. Потому что код читаемый, понятно что как работает и зачем нужно - можно оптимизивароть. А когда у тебя все на макросах с goto и небезопасно - там хуй что поймешь и боишься что-то трогать. В итоге у нас на 10-20% быстрее оригинала по разным бенчам. ДА, НА РАСТЕ БЫСТРЕЕ ЧЕМ НА СИ. А секрет прост - раст не меньше чем Си дает контроля за тем, какой там код будет сгенерен. Ты пишешь код, и понимаешь, что у тебя в ассемблере будет в этом месте. При этом type/memory/thread safety и вообще красивые абстракции.

**Comment by ademonov** [comment]
I don't really like the walls of the same text in my chat log. That's does not make any sense. I mean the true sense of that :)

Probably there is a better way to post this as sticker.
Probably, it have to be modified a little, based on triggered message

**Comment by alxrm** [comment]
I'd say this is not how the community should be like, I mean isn't this text offensive to the LGBT+ people? There are no mentions of transgender people or people of color, we should look towards the equality in the industry. Also this text is deeply disturbing for the disabled persons, like, say, golang developers, you see what I mean? It seems like we need the proper code of conduct(aka **CoCk**) to make the jerk-rs environment more friendly for every jerk out there
